language: rust
cache:
  directories:
  - $HOME/.cargo
rust:
- stable
os:
- linux
- osx
matrix:
  allow_failures:
    - os: osx
#before_install:
#  scripts/travis_setup.sh
install:
- sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
- sudo apt-get -qq update
- sudo apt-get install -y mosquitto
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- export PATH="$HOME/.cargo/bin:$PATH"
- rustup toolchain install stable
- rustup default stable
- rustc -V
- cargo -V
branches:
  only:
  - master
before_script:
  - sudo cp scripts/mosquitto.conf /etc/mosquitto/conf.d/mosquitto.conf
  - sudo service mosquitto restart
script:
- cargo build
- cargo test
- cargo doc --no-deps
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash docdeploy.sh
  - sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev && wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && sudo make install && cd ../.. && kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/rumqtt-*
notifications:
  email:
    on_success: never
env:
  global:
    secure: WOIz8O/G0UBwpllVPeQMN8DUNi0SaiKj9c0oGBjRUkO2KVaIobG3I9l9lR+o2VslW+wRbvOS73XVKMOI2jDm1tQKnG4e4Aso85hEC0OvvxZG/gTRhs6Ef6sVmgP+wsic8+JMOYMcnBNm/46VpFw9QETFRQ9XOV7cUvPXPp+5aSVub+mr/ARXKb0hSQTxAKTve9EZZdcMUihdxIdh/1vmTs2SCmozzMEKl6jqPMxakgKderSEFvaK3lrtdJTONxpmvkd9NSoG2TBXvpKnAhKLvyfFnJi08Kz8x4QVnUG7WKuzO2UjXcZeAALAh66s2I2vhzzPr2oZgGJMrZYAAtmxHPtX6MXdtaaR1ZgzLbE7ijsQjX3JQDRnZtWAXp6q3+jHEGq7Gj/M0cWF9oKKceDApJKtitvF+HBYoVJ8awVJIxBuBfLEVa8Yg9W6/tsiu+ZzdetRuwQUAbtztv3/MLvSPaEJCVF+U9eXwpo2hbY5uVQZV/iJUkKZI3yJs/gN9rA0Ahqgfd+tEAGoQYXVhIbSijPLSBo80Z9bq2HIlrLtB9x614Q7WeKLMdgegTS89BexQ58JmCR4Sno/b/hvmfJlX997NqNj9S0B6FjoObtKJduiRXdM/7zQ36PGQ74NmAi1ebzuh5qDFusiTXnZeIg3JVzxO25KxeziNvHtglKi/wg=
